### ISSUE TITLE
scripts/extract_all.sh is missing  execute permissions

### ISSUE THREAD

**Issue by jzizka91** [iTob191/aowow-extractor#1]
Hi.

Thanks for `aowow-extractor`. It was helpful.

When trying out  aow_extractor I encountered an error of Docker not being able to execute `./extract_all.sh` when the container is run. By examining `Dockerfile` I noticed the script is missing execute permissions.

I suggest granting execute permissions to all the scripts in `scripts/*` or at least to `scripts/extract_all.sh`. in Dockerfile -> `RUN chmod +x ./extract/*` or `RUN chmod +x ./extract/extract_all.sh`

```
COPY ./scripts /extract

RUN chmod +x ./extract/*` #or RUN chmod +x ./extract/extract_all.sh

WORKDIR /extract
ENTRYPOINT [ "./extract_all.sh" ]
CMD [ "--help" ]
```

**Comment by iTob191** [comment]
Thanks for the report, should be fixed
