### ISSUE TITLE
Suggestion: Include `/Interface/Glues/Credits/` pattern

### ISSUE THREAD

**Issue by jzizka91** [iTob191/aowow-extractor#2]
Hi.

I noticed that extractor doesn't extract this path `/Interface/Glues/Credits/`. Based on the aowow install [guide](https://github.com/Sarjuuk/aowow?tab=readme-ov-file#4-extract-the-client-archives-mpqs) it should be included for the aowow setup. My suggestion is to include the path to the `PATTERNS_LOCALE_SHARED` array so it can be extracted as well.

```
PATTERNS_LOCALE_SHARED=(
	"interface\\talentframe\\*.blp"
	"interface\\icons\\*.blp"
	"interface\\spellbook\\*.blp"
	"interface\\paperdoll\\*.blp"
	"interface\\pictures\\*.blp"
	"interface\\PvPRankBadges\\*.blp"
	"interface\\FlavorImages\\*.blp"
	"interface\\glues\\charactercreate\\*.blp"
	"interface\\glues\\credits\\*.blp"
	"interface\\calendar\\holidays\\*.blp"
	"interface\\pvpframe\\*.blp"
)
```

**Comment by Sarjuuk** [comment]
`/Interface/Glues/Credits/` is optional and was never used by aowow itself.
No idea why i originally put that up there with the other, required paths. In any case, it's moved now.

**Comment by jzizka91** [comment]
> `/Interface/Glues/Credits/` is optional and was never used by aowow itself. No idea why i originally put that up there with the other, required paths. In any case, it's moved now.

Alright. If `/Interface/Glues/Credits/` was never needed there is no point added to the script. :)
